import type { ObservationCategory, SkillId } from "@/lib/forge/types";

export type KnowledgeChunk = {
  id: string;
  documentId: string;
  title: string;
  kind: "concept" | "diagnostic" | "procedure" | "safety";
  text: string;
  concepts: string[];
  skills: SkillId[];
  difficulty: number;
  mistakeTypes: ObservationCategory[];
  prerequisites: string[];
  sourceIds: string[];
};

const chunk = (
  documentId: string,
  title: string,
  kind: KnowledgeChunk["kind"],
  text: string,
  concepts: string[],
  skills: SkillId[],
  difficulty: number,
  sourceIds: string[],
  mistakeTypes: ObservationCategory[] = [],
  prerequisites: string[] = [],
  idOverride?: string,
): KnowledgeChunk => ({
  id: idOverride ?? `${documentId}-${kind}`,
  documentId,
  title,
  kind,
  text,
  concepts,
  skills,
  difficulty,
  mistakeTypes,
  prerequisites,
  sourceIds,
});

/** V30 local, auditable corpus. Text is original instructional material. */
export const KNOWLEDGE_CORPUS: readonly KnowledgeChunk[] = [
  chunk(
    "paths",
    "Paths: absolute vs relative",
    "concept",
    "An absolute Linux path begins at /. A relative path is interpreted from the current working directory. pwd establishes the starting point; ls can reveal the next path component.",
    ["path", "absolute", "relative", "pwd", "ls", "cwd"],
    ["filesystem"],
    1,
    ["linuxjourney"],
    ["WRONG_PATH", "MISREAD_QUESTION"],
    [],
    "fs-paths",
  ),
  chunk(
    "paths",
    "Diagnosing a missing path",
    "diagnostic",
    "When a path fails, do not immediately change commands. Compare the intended target with pwd, inspect the parent directory, and check spelling and object type.",
    ["path", "pwd", "ls", "diagnostic"],
    ["filesystem"],
    1,
    ["linuxjourney"],
    ["WRONG_PATH", "WRONG_FILENAME", "TYPO"],
  ),
  chunk(
    "creation",
    "Files and directories",
    "concept",
    "mkdir creates directories and touch can create an empty file. Separate the parent directory from the final object so each part of a multi-step objective can be verified.",
    ["mkdir", "touch", "file", "directory", "parent"],
    ["filesystem"],
    1,
    ["linuxjourney", "overthewire"],
    ["WRONG_PATH", "WRONG_FILENAME"],
  ),
  chunk(
    "permissions",
    "Permission classes",
    "concept",
    "Unix permissions are evaluated for owner, group, and others. For each class, read is 4, write is 2, and execute is 1 in numeric notation.",
    ["chmod", "read", "write", "execute", "owner", "group", "others", "numeric"],
    ["permissions"],
    2,
    ["linuxjourney"],
    ["WRONG_ARGUMENT", "CONCEPT_CONFUSION"],
  ),
  chunk(
    "permissions",
    "Diagnosing chmod mistakes",
    "diagnostic",
    "Inspect the current mode before choosing a replacement. Translate the requested access class-by-class, then verify with ls -l or an equivalent observation.",
    ["chmod", "ls", "permissions", "verify"],
    ["permissions"],
    2,
    ["linuxjourney"],
    ["WRONG_ARGUMENT", "CONCEPT_CONFUSION", "WRONG_PATH"],
  ),
  chunk(
    "loops",
    "Iteration is part of method",
    "concept",
    "A shell loop repeats a command block across values or while a condition holds. If a task explicitly requires a loop, identical output alone does not demonstrate the requested technique.",
    ["for", "while", "loop", "iteration", "do", "done"],
    ["iteration", "shell-scripting"],
    2,
    ["overthewire"],
    ["SKILL_BYPASS", "CONCEPT_CONFUSION"],
  ),
  chunk(
    "loops",
    "Loop diagnosis",
    "diagnostic",
    "Identify the changing value, the command executed per iteration, and the stopping condition. Then test the smallest loop that demonstrates the intended behavior.",
    ["iteration", "variable", "condition", "loop"],
    ["iteration", "shell-scripting"],
    2,
    ["overthewire"],
    ["CONCEPT_CONFUSION", "WRONG_ARGUMENT"],
  ),
  chunk(
    "errors",
    "Read the shell error",
    "diagnostic",
    "A non-zero exit and stderr are evidence. Classify the failure before retrying: command, argument, path, filename, permission, or state. One precise observation is usually more useful than repeated guesses.",
    ["stderr", "exit", "error", "diagnostic", "permission"],
    ["shell-scripting", "filesystem"],
    1,
    ["linuxjourney", "overthewire"],
    ["RANDOM_TRIAL_AND_ERROR", "WRONG_COMMAND", "WRONG_ARGUMENT"],
  ),
  chunk(
    "processes",
    "Process identity",
    "concept",
    "A running process has a PID and state. Inspect process identity before acting on it; a signal affects the selected process rather than an abstract command name.",
    ["process", "pid", "ps", "signal", "kill"],
    ["processes"],
    2,
    ["linuxjourney"],
    ["WRONG_ARGUMENT", "CONCEPT_CONFUSION"],
  ),
  chunk(
    "network",
    "Layered network observation",
    "procedure",
    "Start with local interface and address state, then inspect routes, name resolution, reachability, and service/socket state. Change configuration only after the failing layer is identified.",
    ["ip", "route", "dns", "ping", "ss", "socket"],
    ["networking"],
    2,
    ["linuxjourney", "nmap-book"],
    ["CONCEPT_CONFUSION", "RANDOM_TRIAL_AND_ERROR"],
  ),
  chunk(
    "web",
    "HTTP request and response",
    "concept",
    "HTTP security reasoning separates client-controlled input, request metadata, server processing, response metadata, and state such as cookies or sessions.",
    ["http", "request", "response", "header", "cookie", "session"],
    ["networking", "hardening"],
    3,
    ["portswigger"],
    ["CONCEPT_CONFUSION"],
  ),
  chunk(
    "safety",
    "Authorized lab methodology",
    "safety",
    "Security actions must stay within the authorized training environment. Establish scope, observe first, validate impact safely, preserve evidence, and stop when an action would leave the modeled lab boundary.",
    ["scope", "authorized", "enumeration", "evidence", "cleanup"],
    ["networking", "hardening"],
    3,
    ["mitre-attack", "picoctf"],
    ["UNSAFE_APPROACH"],
    [],
    "security-method",
  ),
  chunk(
    "security",
    "Authorized security methodology",
    "procedure",
    "Use a deliberate security workflow: confirm authorization and scope, observe the target, form a hypothesis, validate it with the least invasive authorized action, record evidence, and stop at the training boundary.",
    ["authorization", "scope", "methodology", "enumeration", "evidence", "least-invasive"],
    ["networking", "hardening"],
    3,
    ["mitre-attack", "picoctf"],
    ["UNSAFE_APPROACH"],
    [],
    "security-procedure",
  ),
];
