export {
  TRUSTED_QUESTION_SOURCES as QUESTION_SOURCE_REGISTRY,
  getTrustedQuestionSource,
} from "./question-intelligence";
export type { TrustedQuestionSource } from "./question-intelligence";

/** Broad source/topic catalogue used by the adaptive exercise generator.
 * The catalogue deliberately references public learning sources instead of
 * copying their question text. The generator creates fresh tasks from the
 * learner model and may cite a source as background.
 */
export const QUESTION_SOURCES = [
  {
    id: "kali-training",
    name: "Kali Training",
    url: "https://kali.training/",
    scope: "Official Kali Linux training and practice",
  },
  {
    id: "linuxjourney",
    name: "Linux Journey",
    url: "https://labex.io/linuxjourney",
    scope: "Linux fundamentals and administration",
  },
  {
    id: "overthewire",
    name: "OverTheWire",
    url: "https://overthewire.org/wargames/bandit/",
    scope: "Command line and security fundamentals",
  },
  {
    id: "picoctf",
    name: "picoCTF",
    url: "https://picoctf.org/",
    scope: "Hands-on cybersecurity challenges",
  },
  {
    id: "portswigger",
    name: "PortSwigger Web Security Academy",
    url: "https://portswigger.net/web-security",
    scope: "Web security concepts and labs",
  },
  {
    id: "mitre-attack",
    name: "MITRE ATT&CK",
    url: "https://attack.mitre.org/",
    scope: "Adversary tactics and techniques",
  },
  {
    id: "nmap-book",
    name: "Nmap Reference",
    url: "https://nmap.org/book/",
    scope: "Network discovery and administration",
  },
] as const;

const domains = {
  linux: [
    "filesystem navigation",
    "paths and globbing",
    "file creation",
    "file metadata",
    "permissions",
    "ownership",
    "links",
    "archives",
    "text processing",
    "shell history",
  ],
  shell: [
    "variables",
    "quoting",
    "redirection",
    "pipes",
    "conditionals",
    "for loops",
    "while loops",
    "functions",
    "exit codes",
    "argument parsing",
  ],
  processes: [
    "process states",
    "jobs",
    "signals",
    "background services",
    "resource inspection",
    "process trees",
    "logs",
    "scheduling",
    "limits",
    "service troubleshooting",
  ],
  networking: [
    "IP addressing",
    "routing",
    "DNS",
    "ports",
    "sockets",
    "HTTP basics",
    "TLS basics",
    "firewall concepts",
    "network diagnostics",
    "packet reasoning",
  ],
  admin: [
    "package management",
    "users",
    "groups",
    "sudo policy",
    "SSH configuration",
    "cron",
    "systemd concepts",
    "storage",
    "mounts",
    "backup strategy",
  ],
  security: [
    "least privilege",
    "hardening",
    "secrets handling",
    "authentication",
    "authorization",
    "audit logs",
    "attack surface",
    "misconfiguration analysis",
    "secure defaults",
    "incident triage",
  ],
  blueTeam: [
    "log analysis",
    "IOC reasoning",
    "detection rules",
    "process anomalies",
    "persistence indicators",
    "network anomalies",
    "file integrity",
    "account anomalies",
    "containment",
    "post-incident review",
  ],
  web: [
    "HTTP requests",
    "sessions",
    "access control",
    "input validation",
    "XSS concepts",
    "SQL injection concepts",
    "CSRF concepts",
    "SSRF concepts",
    "security headers",
    "secure API design",
  ],
  pentest: [
    "recon methodology",
    "service enumeration",
    "credential hygiene",
    "privilege escalation concepts",
    "web enumeration",
    "misconfiguration discovery",
    "exploit reasoning",
    "proof of impact",
    "cleanup",
    "reporting",
  ],
  crypto: [
    "hashing",
    "encoding vs encryption",
    "password storage",
    "key management",
    "TLS trust",
    "signatures",
    "entropy",
    "randomness",
    "integrity",
    "common crypto mistakes",
  ],
  forensics: [
    "timeline reasoning",
    "file metadata",
    "log timelines",
    "process evidence",
    "network evidence",
    "persistence artifacts",
    "deleted-file concepts",
    "hash comparison",
    "evidence preservation",
    "case notes",
  ],
  advanced: [
    "containers",
    "namespaces",
    "capabilities",
    "sandboxing",
    "Linux ACLs",
    "SELinux/AppArmor concepts",
    "kernel attack surface",
    "secure automation",
    "threat modeling",
    "multi-stage incident simulation",
  ],
} as const;

export const QUESTION_TOPICS = Object.entries(domains).flatMap(([domain, topics]) =>
  topics.map((topic) => ({ domain, topic })),
);

export type QuestionTopic = (typeof QUESTION_TOPICS)[number];
