-- M4: persistent learner Linux environment state.
-- lab_instances.environment_id remains the canonical environment identity. This
-- table adds durable persistence lifecycle/integrity state without conflating it
-- with ephemeral runtime identity or terminal sessions.

CREATE TABLE IF NOT EXISTS public.lab_environment_state (
  environment_id text PRIMARY KEY,
  instance_id uuid NOT NULL UNIQUE REFERENCES public.lab_instances(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lab_id uuid NOT NULL REFERENCES public.learner_labs(id) ON DELETE CASCADE,
  state text NOT NULL CHECK (state IN ('PROVISIONING','READY','ACTIVE','STOPPING','STOPPED','FAILED','QUARANTINED','DESTROYING','DESTROYED')),
  environment_generation bigint NOT NULL DEFAULT 1 CHECK (environment_generation >= 1),
  artifact_version bigint NOT NULL DEFAULT 1 CHECK (artifact_version >= 1),
  artifact_ref text,
  integrity_status text NOT NULL DEFAULT 'UNVERIFIED' CHECK (integrity_status IN ('UNVERIFIED','VERIFIED','FAILED')),
  integrity_fingerprint text,
  failure_reason text,
  last_persisted_at timestamptz,
  last_verified_at timestamptz,
  last_restored_at timestamptz,
  destroyed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS lab_environment_state_user_idx
  ON public.lab_environment_state(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS lab_environment_state_lab_idx
  ON public.lab_environment_state(lab_id, state);

ALTER TABLE public.lab_environment_state ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lab_environment_state_select_own ON public.lab_environment_state;
CREATE POLICY lab_environment_state_select_own ON public.lab_environment_state
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS lab_environment_state_insert_own ON public.lab_environment_state;
CREATE POLICY lab_environment_state_insert_own ON public.lab_environment_state
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS lab_environment_state_update_own ON public.lab_environment_state;
CREATE POLICY lab_environment_state_update_own ON public.lab_environment_state
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
REVOKE DELETE ON public.lab_environment_state FROM authenticated, anon;
GRANT SELECT, INSERT, UPDATE ON public.lab_environment_state TO authenticated;
GRANT ALL ON public.lab_environment_state TO service_role;

DROP TRIGGER IF EXISTS lab_environment_state_updated_at ON public.lab_environment_state;
CREATE TRIGGER lab_environment_state_updated_at
BEFORE UPDATE ON public.lab_environment_state
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.lab_environment_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  environment_id text NOT NULL REFERENCES public.lab_environment_state(environment_id) ON DELETE CASCADE,
  instance_id uuid NOT NULL REFERENCES public.lab_instances(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('CREATED','READY','STARTED','STOPPING','STOPPED','RESTARTED','RESET','RESTORED','VERIFIED','QUARANTINED','DESTROYING','DESTROYED','RECOVERY_STARTED','RECOVERY_COMPLETED','RECOVERY_FAILED')),
  environment_generation bigint NOT NULL,
  artifact_version bigint NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS lab_environment_events_env_idx
  ON public.lab_environment_events(user_id, environment_id, created_at ASC);
ALTER TABLE public.lab_environment_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lab_environment_events_select_own ON public.lab_environment_events;
CREATE POLICY lab_environment_events_select_own ON public.lab_environment_events
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
REVOKE INSERT, UPDATE, DELETE ON public.lab_environment_events FROM authenticated, anon;
GRANT SELECT ON public.lab_environment_events TO authenticated;
GRANT ALL ON public.lab_environment_events TO service_role;
