-- V48 stateful realistic scenario persistence. Scenario execution remains behind V44/V45 boundaries.
create table if not exists public.scenarios (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, scenario_id text not null, version integer not null, definition jsonb not null, created_at timestamptz not null default now(), unique(user_id,scenario_id,version));
create table if not exists public.scenario_sessions (id uuid primary key default gen_random_uuid(), scenario_id uuid not null references public.scenarios(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, lab_id text not null, runtime_id text not null, state text not null default 'READY', world_state jsonb not null, started_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now());
create table if not exists public.scenario_events (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.scenario_sessions(id) on delete cascade, scenario_id uuid not null references public.scenarios(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, event_id text not null, event_type text not null, runtime_id text not null, evidence jsonb not null, occurred_at timestamptz not null default now(), unique(session_id,event_id));
create table if not exists public.scenario_checkpoints (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.scenario_sessions(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, checkpoint_id text not null, name text not null, world_state jsonb not null, created_at timestamptz not null default now(), unique(session_id,checkpoint_id));

alter table public.scenarios enable row level security; alter table public.scenario_sessions enable row level security; alter table public.scenario_events enable row level security; alter table public.scenario_checkpoints enable row level security;
create policy "scenario owner access" on public.scenarios for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "scenario session owner access" on public.scenario_sessions for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "scenario event owner read" on public.scenario_events for select to authenticated using (user_id=auth.uid());
create policy "scenario checkpoint owner access" on public.scenario_checkpoints for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
