-- M5: immutable semantic exercise verification and learner attempt evidence.
create table if not exists public.lab_exercise_attempts (
  attempt_id uuid primary key,
  user_id uuid not null,
  lab_id uuid not null,
  environment_id text not null,
  exercise_id text not null,
  question_id text not null,
  question_variant_id text,
  exercise_version integer not null check (exercise_version > 0),
  semantic_fingerprint text not null,
  completion_mode text,
  consumed boolean not null default false,
  hints_used integer not null default 0 check (hints_used >= 0),
  solution_revealed boolean not null default false,
  verdict text not null,
  created_at timestamptz not null default now()
);

create index if not exists lab_exercise_attempts_user_exercise_idx
  on public.lab_exercise_attempts(user_id, exercise_id, created_at desc);
create index if not exists lab_exercise_attempts_question_idx
  on public.lab_exercise_attempts(user_id, question_id, created_at desc);
create index if not exists lab_exercise_attempts_semantic_idx
  on public.lab_exercise_attempts(user_id, semantic_fingerprint);

create table if not exists public.lab_exercise_verifications (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.lab_exercise_attempts(attempt_id) on delete restrict,
  user_id uuid not null,
  environment_id text not null,
  environment_generation integer not null check (environment_generation > 0),
  runtime_lifecycle_generation integer,
  verifier_version text not null,
  contract_version integer not null check (contract_version > 0),
  verdict text not null,
  score integer not null check (score between 0 and 100),
  failure_classification text,
  evidence jsonb not null default '{}'::jsonb,
  verified_at timestamptz not null default now(),
  unique(attempt_id, verifier_version, contract_version)
);

create index if not exists lab_exercise_verifications_user_idx
  on public.lab_exercise_verifications(user_id, verified_at desc);
create index if not exists lab_exercise_verifications_environment_idx
  on public.lab_exercise_verifications(user_id, environment_id, environment_generation);

create table if not exists public.lab_exercise_requirement_results (
  id bigint generated by default as identity primary key,
  verification_id bigint not null references public.lab_exercise_verifications(id) on delete cascade,
  user_id uuid not null,
  requirement_id text not null,
  met boolean not null,
  evidence text not null,
  observed jsonb,
  created_at timestamptz not null default now(),
  unique(verification_id, requirement_id)
);

create index if not exists lab_exercise_requirement_results_user_idx
  on public.lab_exercise_requirement_results(user_id, created_at desc);

alter table public.lab_exercise_attempts enable row level security;
alter table public.lab_exercise_verifications enable row level security;
alter table public.lab_exercise_requirement_results enable row level security;

revoke all on public.lab_exercise_attempts from anon;
revoke all on public.lab_exercise_verifications from anon;
revoke all on public.lab_exercise_requirement_results from anon;

create policy "learners read own exercise attempts"
  on public.lab_exercise_attempts for select to authenticated
  using (auth.uid() = user_id);
create policy "learners read own exercise verifications"
  on public.lab_exercise_verifications for select to authenticated
  using (auth.uid() = user_id);
create policy "learners read own requirement results"
  on public.lab_exercise_requirement_results for select to authenticated
  using (auth.uid() = user_id);

-- Verification records are written only by the server-side service role.
create policy "service role manages exercise attempts"
  on public.lab_exercise_attempts for all to service_role
  using (true) with check (true);
create policy "service role manages exercise verifications"
  on public.lab_exercise_verifications for all to service_role
  using (true) with check (true);
create policy "service role manages requirement results"
  on public.lab_exercise_requirement_results for all to service_role
  using (true) with check (true);
