-- M3: terminal & lab control plane persistence.
-- Terminal sessions are learner-owned, short-lived control-plane objects.

CREATE TABLE IF NOT EXISTS public.lab_terminal_sessions (
  session_id text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  instance_id uuid NOT NULL REFERENCES public.lab_instances(id) ON DELETE CASCADE,
  runtime_id text NOT NULL,
  lab_id uuid NOT NULL REFERENCES public.learner_labs(id) ON DELETE CASCADE,
  shell text NOT NULL CHECK (shell IN ('bash','zsh','sh')),
  cwd text NOT NULL,
  state text NOT NULL DEFAULT 'CREATED' CHECK (state IN ('CREATED','AUTHORIZED','CONNECTED','DISCONNECTED','CLOSED','EXPIRED','FAILED')),
  binding_generation bigint NOT NULL CHECK (binding_generation >= 1),
  runtime_lifecycle_generation bigint NOT NULL CHECK (runtime_lifecycle_generation >= 1),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  expires_at timestamptz NOT NULL,
  closed_at timestamptz,
  PRIMARY KEY (user_id, session_id)
);

CREATE INDEX IF NOT EXISTS lab_terminal_sessions_instance_idx
  ON public.lab_terminal_sessions (instance_id, created_at DESC);
CREATE INDEX IF NOT EXISTS lab_terminal_sessions_active_idx
  ON public.lab_terminal_sessions (user_id, instance_id, state)
  WHERE state IN ('CREATED','AUTHORIZED','CONNECTED','DISCONNECTED');

ALTER TABLE public.lab_terminal_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "learners can view own terminal sessions" ON public.lab_terminal_sessions;
CREATE POLICY "learners can view own terminal sessions"
  ON public.lab_terminal_sessions FOR SELECT TO authenticated
  USING (user_id = auth.uid());
DROP POLICY IF EXISTS "learners can create own terminal sessions" ON public.lab_terminal_sessions;
CREATE POLICY "learners can create own terminal sessions"
  ON public.lab_terminal_sessions FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (SELECT 1 FROM public.lab_instances li WHERE li.id = instance_id AND li.user_id = auth.uid())
    AND EXISTS (SELECT 1 FROM public.learner_labs ll WHERE ll.id = lab_id AND ll.user_id = auth.uid())
  );
DROP POLICY IF EXISTS "learners can update own terminal sessions" ON public.lab_terminal_sessions;
CREATE POLICY "learners can update own terminal sessions"
  ON public.lab_terminal_sessions FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());
REVOKE DELETE ON public.lab_terminal_sessions FROM authenticated, anon;
GRANT SELECT, INSERT, UPDATE ON public.lab_terminal_sessions TO authenticated;
GRANT ALL ON public.lab_terminal_sessions TO service_role;

DROP TRIGGER IF EXISTS lab_terminal_sessions_updated_at ON public.lab_terminal_sessions;
CREATE TRIGGER lab_terminal_sessions_updated_at
BEFORE UPDATE ON public.lab_terminal_sessions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Extend the durable operation vocabulary for atomic restart intent.
ALTER TABLE public.lab_control_operations
  DROP CONSTRAINT IF EXISTS lab_control_operations_kind_check;
ALTER TABLE public.lab_control_operations
  ADD CONSTRAINT lab_control_operations_kind_check
  CHECK (kind IN ('CREATE','START','STOP','RESTART','RESET','PAUSE','RESUME','SNAPSHOT','RESTORE','DESTROY','EXPIRE','RECONCILE'));

CREATE TABLE IF NOT EXISTS public.lab_terminal_session_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  instance_id uuid NOT NULL REFERENCES public.lab_instances(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('CREATED','AUTHORIZED','CONNECTED','DISCONNECTED','RECONNECTED','CLOSED','EXPIRED','FAILED','REVOKED')),
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS lab_terminal_session_events_session_idx
  ON public.lab_terminal_session_events (user_id, session_id, created_at ASC);
ALTER TABLE public.lab_terminal_session_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "learners can view own terminal session events" ON public.lab_terminal_session_events;
CREATE POLICY "learners can view own terminal session events"
  ON public.lab_terminal_session_events FOR SELECT TO authenticated
  USING (user_id = auth.uid());
REVOKE INSERT, UPDATE, DELETE ON public.lab_terminal_session_events FROM authenticated, anon;
GRANT SELECT ON public.lab_terminal_session_events TO authenticated;
GRANT ALL ON public.lab_terminal_session_events TO service_role;
