CREATE TABLE public.learning_sessions (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'PAUSED', 'COMPLETED', 'ABANDONED')),
  phase text NOT NULL DEFAULT 'ORIENT' CHECK (phase IN ('ORIENT', 'TEACH', 'PRACTICE', 'VERIFY', 'REFLECT', 'COMPLETE')),
  activity_id text,
  challenge_id text,
  plan jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_verification jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE INDEX learning_sessions_user_updated_idx
  ON public.learning_sessions (user_id, updated_at DESC);

CREATE UNIQUE INDEX learning_sessions_one_active_per_user_idx
  ON public.learning_sessions (user_id)
  WHERE status IN ('ACTIVE', 'PAUSED');

CREATE TABLE public.learning_session_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL REFERENCES public.learning_sessions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  phase text NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX learning_session_events_session_created_idx
  ON public.learning_session_events (session_id, created_at ASC);

GRANT SELECT, INSERT, UPDATE ON public.learning_sessions TO authenticated;
GRANT SELECT, INSERT ON public.learning_session_events TO authenticated;
GRANT ALL ON public.learning_sessions TO service_role;
GRANT ALL ON public.learning_session_events TO service_role;

ALTER TABLE public.learning_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_session_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY learning_sessions_select_own ON public.learning_sessions
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY learning_sessions_insert_own ON public.learning_sessions
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY learning_sessions_update_own ON public.learning_sessions
  FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY learning_session_events_select_own ON public.learning_session_events
  FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY learning_session_events_insert_own ON public.learning_session_events
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

CREATE TRIGGER learning_sessions_set_updated_at
  BEFORE UPDATE ON public.learning_sessions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
