-- V44: durable production lab control operations and append-only audit events.
-- Operations are learner-owned intents; provider execution remains outside SQL.

CREATE TABLE IF NOT EXISTS public.lab_control_operations (
  id uuid PRIMARY KEY,
  instance_id uuid NOT NULL REFERENCES public.lab_instances(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('CREATE','START','STOP','RESET','PAUSE','RESUME','SNAPSHOT','RESTORE','DESTROY','EXPIRE','RECONCILE')),
  status text NOT NULL DEFAULT 'QUEUED' CHECK (status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED','UNKNOWN')),
  idempotency_key text NOT NULL,
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  lease_until timestamptz,
  worker_id text,
  result_ref text,
  error text,
  UNIQUE (user_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS lab_control_operations_instance_idx
  ON public.lab_control_operations (instance_id, created_at DESC);
CREATE INDEX IF NOT EXISTS lab_control_operations_queue_idx
  ON public.lab_control_operations (status, created_at ASC)
  WHERE status IN ('QUEUED','UNKNOWN');
CREATE INDEX IF NOT EXISTS lab_control_operations_lease_idx
  ON public.lab_control_operations (lease_until)
  WHERE status = 'RUNNING';

ALTER TABLE public.lab_control_operations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "learners can view own control operations" ON public.lab_control_operations;
CREATE POLICY "learners can view own control operations"
  ON public.lab_control_operations FOR SELECT TO authenticated
  USING (user_id = auth.uid());
DROP POLICY IF EXISTS "learners can create own control operations" ON public.lab_control_operations;
CREATE POLICY "learners can create own control operations"
  ON public.lab_control_operations FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (SELECT 1 FROM public.lab_instances li WHERE li.id = instance_id AND li.user_id = auth.uid())
  );
DROP POLICY IF EXISTS "learners can update own active control operations" ON public.lab_control_operations;
CREATE POLICY "learners can update own active control operations"
  ON public.lab_control_operations FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());
REVOKE DELETE ON public.lab_control_operations FROM authenticated, anon;
GRANT SELECT, INSERT, UPDATE ON public.lab_control_operations TO authenticated;

CREATE TABLE IF NOT EXISTS public.lab_control_operation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id uuid NOT NULL REFERENCES public.lab_control_operations(id) ON DELETE CASCADE,
  instance_id uuid NOT NULL REFERENCES public.lab_instances(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('CREATED','CLAIMED','HEARTBEAT','SUCCEEDED','FAILED','RECOVERED','RECONCILED','EXPIRED','CANCELLED')),
  from_status text,
  to_status text,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS lab_control_operation_events_operation_idx
  ON public.lab_control_operation_events (operation_id, created_at ASC);
ALTER TABLE public.lab_control_operation_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "learners can view own control operation events" ON public.lab_control_operation_events;
CREATE POLICY "learners can view own control operation events"
  ON public.lab_control_operation_events FOR SELECT TO authenticated
  USING (user_id = auth.uid());
REVOKE INSERT, UPDATE, DELETE ON public.lab_control_operation_events FROM authenticated, anon;
GRANT SELECT ON public.lab_control_operation_events TO authenticated;

CREATE OR REPLACE FUNCTION public.lab_control_operations_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS lab_control_operations_updated_at ON public.lab_control_operations;
CREATE TRIGGER lab_control_operations_updated_at
BEFORE UPDATE ON public.lab_control_operations
FOR EACH ROW EXECUTE FUNCTION public.lab_control_operations_set_updated_at();

-- Runtime binding and health projection. These are control-plane metadata only;
-- the runtime remains the source of truth for actual machine state.
ALTER TABLE public.lab_instances
  ADD COLUMN IF NOT EXISTS runtime_node_id text,
  ADD COLUMN IF NOT EXISTS runtime_binding_generation integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS resource_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS last_reconciled_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_health_at timestamptz;

CREATE INDEX IF NOT EXISTS lab_instances_runtime_node_idx ON public.lab_instances (runtime_node_id)
  WHERE runtime_node_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS lab_instances_health_idx ON public.lab_instances (last_health_at)
  WHERE status NOT IN ('STOPPED','EXPIRED');

CREATE OR REPLACE FUNCTION public.lab_control_operation_audit()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_event text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_event := 'CREATED';
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    v_event := CASE NEW.status
      WHEN 'RUNNING' THEN 'CLAIMED'
      WHEN 'SUCCEEDED' THEN 'SUCCEEDED'
      WHEN 'FAILED' THEN 'FAILED'
      WHEN 'UNKNOWN' THEN 'RECOVERED'
      WHEN 'CANCELLED' THEN 'CANCELLED'
      ELSE 'HEARTBEAT'
    END;
  ELSE
    v_event := 'HEARTBEAT';
  END IF;

  INSERT INTO public.lab_control_operation_events (
    operation_id, instance_id, user_id, event_type, from_status, to_status, data
  ) VALUES (
    NEW.id, NEW.instance_id, NEW.user_id, v_event,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.status END,
    NEW.status,
    jsonb_build_object('attempt', NEW.attempt, 'workerId', NEW.worker_id)
  );
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS lab_control_operation_audit ON public.lab_control_operations;
CREATE TRIGGER lab_control_operation_audit
AFTER INSERT OR UPDATE ON public.lab_control_operations
FOR EACH ROW EXECUTE FUNCTION public.lab_control_operation_audit();

-- Internal worker protocol for asynchronous/recovery processing.
CREATE OR REPLACE FUNCTION public.claim_next_lab_control_operation(
  p_worker_id text,
  p_lease_seconds integer DEFAULT 60
)
RETURNS SETOF public.lab_control_operations
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'internal worker role required'; END IF;
  IF p_worker_id IS NULL OR length(trim(p_worker_id)) = 0 OR p_lease_seconds < 15 OR p_lease_seconds > 300 THEN
    RAISE EXCEPTION 'invalid control operation worker policy';
  END IF;

  RETURN QUERY
  WITH candidate AS (
    SELECT id
    FROM public.lab_control_operations
    WHERE status IN ('QUEUED','UNKNOWN')
      AND (lease_until IS NULL OR lease_until <= now())
      AND attempt < 20
    ORDER BY created_at ASC, id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
  )
  UPDATE public.lab_control_operations op
  SET status = 'RUNNING',
      attempt = op.attempt + 1,
      worker_id = p_worker_id,
      lease_until = now() + make_interval(secs => p_lease_seconds),
      error = NULL
  FROM candidate c
  WHERE op.id = c.id
  RETURNING op.*;
END;
$$;

CREATE OR REPLACE FUNCTION public.heartbeat_lab_control_operation(
  p_operation_id uuid,
  p_worker_id text,
  p_lease_seconds integer DEFAULT 60
)
RETURNS SETOF public.lab_control_operations
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'internal worker role required'; END IF;
  IF p_lease_seconds < 15 OR p_lease_seconds > 300 THEN RAISE EXCEPTION 'invalid control operation lease'; END IF;
  RETURN QUERY
  UPDATE public.lab_control_operations
  SET lease_until = now() + make_interval(secs => p_lease_seconds)
  WHERE id = p_operation_id AND status = 'RUNNING' AND worker_id = p_worker_id AND lease_until > now()
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.recover_expired_lab_control_operations(
  p_now timestamptz DEFAULT now(),
  p_limit integer DEFAULT 100
)
RETURNS SETOF public.lab_control_operations
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.role() <> 'service_role' THEN RAISE EXCEPTION 'internal worker role required'; END IF;
  IF p_limit < 1 OR p_limit > 500 THEN RAISE EXCEPTION 'invalid recovery limit'; END IF;
  RETURN QUERY
  UPDATE public.lab_control_operations
  SET status = 'UNKNOWN',
      lease_until = NULL,
      worker_id = NULL,
      error = 'Control operation lease expired; runtime reconciliation is required.'
  WHERE id IN (
    SELECT id FROM public.lab_control_operations
    WHERE status = 'RUNNING' AND lease_until IS NOT NULL AND lease_until <= p_now
    ORDER BY lease_until ASC, id ASC LIMIT p_limit
    FOR UPDATE SKIP LOCKED
  )
  RETURNING *;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_next_lab_control_operation(text, integer) FROM PUBLIC, authenticated, anon;
REVOKE ALL ON FUNCTION public.heartbeat_lab_control_operation(uuid, text, integer) FROM PUBLIC, authenticated, anon;
REVOKE ALL ON FUNCTION public.recover_expired_lab_control_operations(timestamptz, integer) FROM PUBLIC, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.claim_next_lab_control_operation(text, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.heartbeat_lab_control_operation(uuid, text, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.recover_expired_lab_control_operations(timestamptz, integer) TO service_role;
